"""Create initial tables

Revision ID: a23fbd09cdef
Revises:
Create Date: 2025-02-17 22:15:43.301002

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a23fbd09cdef"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backgrounds",
        sa.Column("proficiencies", sa.JSON(), nullable=False),
        sa.Column("equipment", sa.JSON(), nullable=False),
        sa.Column("feature", sa.JSON(), nullable=False),
        sa.Column("characteristics", sa.JSON(), nullable=False),
        sa.Column("source_book", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backgrounds_id"), "backgrounds", ["id"], unique=False)
    op.create_index(op.f("ix_backgrounds_name"), "backgrounds", ["name"], unique=False)
    op.create_table(
        "classes",
        sa.Column("hit_die", sa.String(length=4), nullable=False),
        sa.Column("primary_ability", sa.JSON(), nullable=False),
        sa.Column("saving_throws", sa.JSON(), nullable=False),
        sa.Column("proficiencies", sa.JSON(), nullable=False),
        sa.Column("starting_equipment", sa.JSON(), nullable=False),
        sa.Column("spellcasting_ability", sa.String(length=20), nullable=True),
        sa.Column("spell_slots_progression", sa.JSON(), nullable=True),
        sa.Column("features_by_level", sa.JSON(), nullable=False),
        sa.Column("source_book", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classes_id"), "classes", ["id"], unique=False)
    op.create_index(op.f("ix_classes_name"), "classes", ["name"], unique=False)
    op.create_table(
        "races",
        sa.Column("ability_score_increase", sa.JSON(), nullable=False),
        sa.Column("age", sa.JSON(), nullable=False),
        sa.Column("size", sa.JSON(), nullable=False),
        sa.Column("speed", sa.JSON(), nullable=False),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("traits", sa.JSON(), nullable=False),
        sa.Column("source_book", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_races_id"), "races", ["id"], unique=False)
    op.create_index(op.f("ix_races_name"), "races", ["name"], unique=False)
    op.create_table(
        "subclasses",
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("features_by_level", sa.JSON(), nullable=False),
        sa.Column("spellcasting_ability", sa.String(length=20), nullable=True),
        sa.Column("source_book", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subclasses_id"), "subclasses", ["id"], unique=False)
    op.create_index(op.f("ix_subclasses_name"), "subclasses", ["name"], unique=False)
    op.create_table(
        "subraces",
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("ability_score_increase", sa.JSON(), nullable=False),
        sa.Column("traits", sa.JSON(), nullable=False),
        sa.Column("source_book", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subraces_id"), "subraces", ["id"], unique=False)
    op.create_index(op.f("ix_subraces_name"), "subraces", ["name"], unique=False)
    op.create_table(
        "characters",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("experience_points", sa.Integer(), nullable=False),
        sa.Column("alignment", sa.String(length=20), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("subrace_id", sa.Integer(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("subclass_id", sa.Integer(), nullable=True),
        sa.Column("background_id", sa.Integer(), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("dexterity", sa.Integer(), nullable=False),
        sa.Column("constitution", sa.Integer(), nullable=False),
        sa.Column("intelligence", sa.Integer(), nullable=False),
        sa.Column("wisdom", sa.Integer(), nullable=False),
        sa.Column("charisma", sa.Integer(), nullable=False),
        sa.Column("hit_points", sa.Integer(), nullable=False),
        sa.Column("max_hit_points", sa.Integer(), nullable=False),
        sa.Column("temporary_hit_points", sa.Integer(), nullable=False),
        sa.Column("armor_class", sa.Integer(), nullable=False),
        sa.Column("initiative", sa.Integer(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("proficiencies", sa.JSON(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("equipment", sa.JSON(), nullable=False),
        sa.Column("spells", sa.JSON(), nullable=True),
        sa.Column("personality", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["background_id"],
            ["backgrounds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subclass_id"],
            ["subclasses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subrace_id"],
            ["subraces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("hashed_password", sa.VARCHAR(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_subraces_name"), table_name="subraces")
    op.drop_index(op.f("ix_subraces_id"), table_name="subraces")
    op.drop_table("subraces")
    op.drop_index(op.f("ix_subclasses_name"), table_name="subclasses")
    op.drop_index(op.f("ix_subclasses_id"), table_name="subclasses")
    op.drop_table("subclasses")
    op.drop_index(op.f("ix_races_name"), table_name="races")
    op.drop_index(op.f("ix_races_id"), table_name="races")
    op.drop_table("races")
    op.drop_index(op.f("ix_classes_name"), table_name="classes")
    op.drop_index(op.f("ix_classes_id"), table_name="classes")
    op.drop_table("classes")
    op.drop_index(op.f("ix_backgrounds_name"), table_name="backgrounds")
    op.drop_index(op.f("ix_backgrounds_id"), table_name="backgrounds")
    op.drop_table("backgrounds")
    # ### end Alembic commands ###
